### ISSUE TITLE
[Bug]: binance wallet -  uco - ARCH>BINANCE

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#54] opened 2023-11-21 22:20 UTC
### Description

Binance wallet 
Send uco from archethic testnet to binance smart chain testnet

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/2c61ebe9-af95-455d-8ccb-e4e01120a1db)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000649f4b58e9052d31e60f22d5dd1714a6b05eb3dfe8fe7ca94ad3bd6a80d1c650",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Binance Smart Chain Testnet",
    "chainId": 97,
    "env": "2-testnet",
    "icon": "BSC.svg",
    "urlExplorerAddress": "https://testnet.bscscan.com/address/",
    "urlExplorerTransaction": "https://testnet.bscscan.com/tx/",
    "providerEndpoint": "https://data-seed-prebsc-1-s1.binance.org:8545",
    "isArchethic": false,
    "nativeCurrency": "BNB",
    "htlcAddress": "0x81533b588c94d39f1b7b5e802ba15ecefd90f91d",
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Universal Coin",
    "tokenAddressSource": "",
    "tokenAddressTarget": "0x5e6554593E4fe61276AD09094f16A6D5133461A5",
    "symbol": "UCO",
    "targetTokenName": "BEP20 - Universal Coin",
    "targetTokenSymbol": "UCO",
    "poolAddressFrom": "000018d60115ece0c7558a46b4693749bf6beab524fddccf9b10b910619e4ee08801",
    "poolAddressTo": "0xacc408CB6D6D9C73C6003269D322cb78150fc137",
    "type": "Native"
  },
  "tokenToBridgeAmount": 0.01,
  "targetAddress": "0xcfab18b977ce44ab71e0ad98531b790d0ce2de74",
  "tokenToBridgeBalance": 191.45547876,
  "tokenBridgedBalance": 0,
  "poolTargetBalance": 0.02975474,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "Connectivity issue.",
    "stack": "null",
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "archethic",
  "currentStep": 5,
  "changeDirectionInProgress": false,
  "timestampExec": 1700604973623,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000649f4b58e9052d31e60f22d5dd1714a6b05eb3dfe8fe7ca94ad3bd6a80d1c650",
  "htlcEVMAddress": "0x81533b588c94d39f1b7b5e802ba15ecefd90f91d",
  "htlcEVMTxAddress": "0xa1902db201bf9022538e5ad5e16be82ddc06a06fc31b6bee2a8bd8acf128f353",
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

binance wallet

**Comment by redDwarf03** [comment] 2024-10-24 06:49
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:49 UTC
Labels: Bug, Invalid, Campaign: Bridge
