### ISSUE TITLE
[Bug]: Metamask wallet - ETH - ETH>ARCH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#60] opened 2023-11-23 00:48 UTC
### Description

Metamask wallet 
Send ETH from sepolia Ethereum testnet to archethic testnet

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/a2466f28-9d1b-43e7-a819-33ebb85bd67f)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "blockchainTo": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": null,
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "tokenToBridge": {
    "name": "Ether",
    "tokenAddressSource": "",
    "tokenAddressTarget": "00003DF600E329199BF3EE8FBE2B8223413D70BCDD97E15089E6A74D94DE3F1173B4",
    "symbol": "ETH",
    "targetTokenName": "Archethic Ether",
    "targetTokenSymbol": "aeETH",
    "poolAddressFrom": "0xcfBA4FA32527bFf23E073406c772e9a8b8D02650",
    "poolAddressTo": "000066706d704329ca8c2a4153991e2ddacc968622ca10217ca14952eb7abb966c30",
    "type": "Native"
  },
  "tokenToBridgeAmount": 0.005,
  "targetAddress": "00001675becda24450fad82114a15b58567979e8e7aea1cffc54ce8c1779513ea2af",
  "tokenToBridgeBalance": 0.07884644185349365,
  "tokenBridgedBalance": 0.0600493,
  "poolTargetBalance": 0,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "FormatException: SyntaxError: Unexpected token 'e', \"[ethjs-rpc]\"... is not valid JSON",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": null,
  "currentStep": 1,
  "changeDirectionInProgress": false,
  "timestampExec": 1700700333518,
  "archethicOracleUCO": null,
  "htlcAEAddress": null,
  "htlcEVMAddress": "0x9b7e283f5d31bd162d6168cc6e0d7a72ca72db72",
  "htlcEVMTxAddress": "0xe3f48c4dbf08533876d80ddba0f5a3d86b23cabb84d8ad768a28a403cce1e76a",
  "secret": [
    231,
    253,
    19,
    20,
    139,
    31,
    126,
    50,
    218,
    31,
    222,
    246,
    12,
    131,
    107,
    208,
    215,
    41,
    179,
    149,
    28,
    199,
    147,
    61,
    102,
    160,
    229,
    13,
    36,
    41,
    223,
    229
  ],
  "safetyModuleFeesRate": 0.5,
  "safetyModuleFeesAddress": "0x57B5Fe2F6A28E108208BA4965d9879FACF629442",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

Metamask

**Comment by redDwarf03** [comment] 2024-03-21 20:23
@RVe74 , Could you precise please your desktop environment (windows, mac, linux ?). The metamask version ? The chrome version ?
Thx

**Comment by RVe74** [comment] 2024-03-26 06:03
Salut,Je viens de voir seulement maintenant tes messages. Je regarde pour te répondre au mieux ce soir après être rentré du travail. Bonne journée.Verdet RichardEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : redDwarf03 ***@***.***> Date : 21/03/2024  21:23  (GMT+01:00) À : archethic-foundation/bug-bounty ***@***.***> Cc : RVe74 ***@***.***>, Mention ***@***.***> Objet : Re: [archethic-foundation/bug-bounty] [Bug]: Metamask wallet - ETH - ETH>ARCH (Issue #60) 
@RVe74 , Could you precise please your desktop environment (windows, mac, linux ?). The metamask version ? The chrome version ?
Thx

**Comment by RVe74** [comment] 2024-03-26 20:52
Voilà 

Windows 10 famille 64 bits (10,0, build 19045)

Chrome  version 121.0.6167.140 (build officiel) (64 bits)

Metamask 11.7.5

**Comment by redDwarf03** [comment] 2024-10-24 06:47
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:47 UTC
Labels: Bug, In triage, Campaign: Bridge
