### ISSUE TITLE
[Bug]: Coinbase wallet - aeETH - ARCH>ETH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#51] opened 2023-11-20 23:35 UTC
Y74### Description

Coinbase wallet
Send AeETH from Achethic testnet to Sepolia ethereum testnet 
2 errors

### Logs / Images

![17005239756228357818910499391684](https://github.com/archethic-foundation/bug-bounty/assets/150965024/6d2aadbf-c6d0-4ee8-b1e6-68f07d06a4d5)

![20231121_003300](https://github.com/archethic-foundation/bug-bounty/assets/150965024/652db1f7-3530-42d7-ab2a-7148ed2be27a)

### Platform

Windows 

### Version of Archethic's wallet

2.3.1

### Version of Archethic's Bridge

0.0.9

### EVM wallet

Coinbase wallet

### Fix

_No response

**Comment by redDwarf03** [comment] 2023-11-21 16:32
we can't reproduce these errors.
Have you a scenario please to help us to reproduce it
Thank you

**Comment by RVe74** [comment] 2023-11-21 20:15
{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000515ce5722313d16ef867e4c7eac3ae653afb971ecfe20f2ef16663f1a3338cb6",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Archethic Ether",
    "tokenAddressSource": "00003DF600E329199BF3EE8FBE2B8223413D70BCDD97E15089E6A74D94DE3F1173B4",
    "tokenAddressTarget": "",
    "symbol": "aeETH",
    "targetTokenName": "Ether",
    "targetTokenSymbol": "ETH",
    "poolAddressFrom": "000066706d704329ca8c2a4153991e2ddacc968622ca10217ca14952eb7abb966c30",
    "poolAddressTo": "0xcfBA4FA32527bFf23E073406c772e9a8b8D02650",
    "type": "Wrapped"
  },
  "tokenToBridgeAmount": 0.005,
  "targetAddress": "0xb8524a45f77241be6b47c2c0d4538099f21bd7d5",
  "tokenToBridgeBalance": 0.0166463,
  "tokenBridgedBalance": 0.05,
  "poolTargetBalance": 4.940975,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "Technical error",
    "stack": "null",
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "archethic",
  "currentStep": 2,
  "changeDirectionInProgress": false,
  "timestampExec": 1700522510365,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000515ce5722313d16ef867e4c7eac3ae653afb971ecfe20f2ef16663f1a3338cb6",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

**Comment by RVe74** [comment] 2023-11-21 20:15
{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": null,
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Archethic Ether",
    "tokenAddressSource": "00003DF600E329199BF3EE8FBE2B8223413D70BCDD97E15089E6A74D94DE3F1173B4",
    "tokenAddressTarget": "",
    "symbol": "aeETH",
    "targetTokenName": "Ether",
    "targetTokenSymbol": "ETH",
    "poolAddressFrom": "000066706d704329ca8c2a4153991e2ddacc968622ca10217ca14952eb7abb966c30",
    "poolAddressTo": "0xcfBA4FA32527bFf23E073406c772e9a8b8D02650",
    "type": "Wrapped"
  },
  "tokenToBridgeAmount": 0.005,
  "targetAddress": "0xb8524a45f77241be6b47c2c0d4538099f21bd7d5",
  "tokenToBridgeBalance": 0.0166463,
  "tokenBridgedBalance": 0.05,
  "poolTargetBalance": 4.940975,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "Technical error",
    "stack": "null",
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "archethic",
  "currentStep": 1,
  "changeDirectionInProgress": false,
  "timestampExec": 1700522631737,
  "archethicOracleUCO": null,
  "htlcAEAddress": null,
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

**Comment by RVe74** [comment] 2023-11-21 20:18
{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000bc796e1b969868dfdc5db1c2d9b6f4fdf781bde2c22b3fa7093f59ca41133866",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Archethic Ether",
    "tokenAddressSource": "00003DF600E329199BF3EE8FBE2B8223413D70BCDD97E15089E6A74D94DE3F1173B4",
    "tokenAddressTarget": "",
    "symbol": "aeETH",
    "targetTokenName": "Ether",
    "targetTokenSymbol": "ETH",
    "poolAddressFrom": "000066706d704329ca8c2a4153991e2ddacc968622ca10217ca14952eb7abb966c30",
    "poolAddressTo": "0xcfBA4FA32527bFf23E073406c772e9a8b8D02650",
    "type": "Wrapped"
  },
  "tokenToBridgeAmount": 0.005,
  "targetAddress": "0xb8524a45f77241be6b47c2c0d4538099f21bd7d5",
  "tokenToBridgeBalance": 0.0166463,
  "tokenBridgedBalance": 0.05,
  "poolTargetBalance": 4.940975,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "ClientException: XMLHttpRequest error., uri=https://testnet.archethic.net/api/rpc",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "evm",
  "currentStep": 3,
  "changeDirectionInProgress": false,
  "timestampExec": 1700522780841,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000bc796e1b969868dfdc5db1c2d9b6f4fdf781bde2c22b3fa7093f59ca41133866",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

**Comment by redDwarf03** [comment] 2024-10-24 06:50
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:50 UTC
Labels: Bug, Needs repro info, Campaign: Bridge
