### ISSUE TITLE
[Bug]: Clover wallet - aeETH - ARCH>ETH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#58] opened 2023-11-23 00:16 UTC
### Description

Clover wallet 
Send aeETH from archethic testnet to Sepolia ethereum testnet 

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/1e13ee7f-8c60-41b8-ae2b-61d75660f581)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000e0e9863950060a421415eb342f58871f936f4b9541b7762a9574c102eb5c00d1",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Universal Coin",
    "tokenAddressSource": "",
    "tokenAddressTarget": "0xCBBd3374090113732393DAE1433Bc14E5233d5d7",
    "symbol": "UCO",
    "targetTokenName": "ERC20 - Universal Coin",
    "targetTokenSymbol": "UCO",
    "poolAddressFrom": "000018d60115ece0c7558a46b4693749bf6beab524fddccf9b10b910619e4ee08801",
    "poolAddressTo": "0x50b8B73327613468e5605eD59B980555DAAC354a",
    "type": "Native"
  },
  "tokenToBridgeAmount": 50,
  "targetAddress": "0x66023a7a80751b8a354b527deb1497199f56be4e",
  "tokenToBridgeBalance": 104.70951625,
  "tokenBridgedBalance": 0,
  "poolTargetBalance": 200181.09874041856,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "FormatException: SyntaxError: Unexpected token 'E', \"Error: {\"m\"... is not valid JSON",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "evm",
  "currentStep": 4,
  "changeDirectionInProgress": false,
  "timestampExec": 1700697873882,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000e0e9863950060a421415eb342f58871f936f4b9541b7762a9574c102eb5c00d1",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

Clover

**Comment by redDwarf03** [comment] 2024-03-21 20:20
Hello @RVe74 , i need your help please.
Sorry but i don't find how to setup sepolia on CLV Wallet with the chrome extension.... Could you explain how you did it please

**Comment by RVe74** [comment] 2024-03-26 21:09
Voilà la procédure pour CLV wallet si je ne m’abuse.

**Comment by redDwarf03** [comment] 2024-03-26 21:27
@RVe74 je n'ai pas reçu la procédure. Pouvez vous me l'envoyer par mail à sylvain@archethic.net svp
Merci

**Comment by redDwarf03** [comment] 2024-10-24 06:48
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:48 UTC
Labels: Bug, In triage, Campaign: Bridge
