### ISSUE TITLE
[Bug]: Coinbase wallet - aeEth - ARCH>BINANCE

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#52] opened 2023-11-21 21:12 UTC
### Description

Wallet coinbase
Send aeETH from archethic tesnet to binance Smart Chain Testnet

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/7cfa6344-5b5f-416e-a83e-ab650914519e)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "000023816eedb1ceb48e745317043b052831ef2a71b41118c3b03501e38fc78b96e8",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Binance Smart Chain Testnet",
    "chainId": 97,
    "env": "2-testnet",
    "icon": "BSC.svg",
    "urlExplorerAddress": "https://testnet.bscscan.com/address/",
    "urlExplorerTransaction": "https://testnet.bscscan.com/tx/",
    "providerEndpoint": "https://data-seed-prebsc-1-s1.binance.org:8545",
    "isArchethic": false,
    "nativeCurrency": "BNB",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Universal Coin",
    "tokenAddressSource": "",
    "tokenAddressTarget": "0x5e6554593E4fe61276AD09094f16A6D5133461A5",
    "symbol": "UCO",
    "targetTokenName": "BEP20 - Universal Coin",
    "targetTokenSymbol": "UCO",
    "poolAddressFrom": "000018d60115ece0c7558a46b4693749bf6beab524fddccf9b10b910619e4ee08801",
    "poolAddressTo": "0xacc408CB6D6D9C73C6003269D322cb78150fc137",
    "type": "Native"
  },
  "tokenToBridgeAmount": 0.02,
  "targetAddress": "0x532bce2c4919788c8ba3d84159714014a4028eeb",
  "tokenToBridgeBalance": 495.44379728,
  "tokenBridgedBalance": 0,
  "poolTargetBalance": 0.02975474,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "FormatException: SyntaxError: Unexpected token 'F', \"Failed to \"... is not valid JSON",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "evm",
  "currentStep": 4,
  "changeDirectionInProgress": false,
  "timestampExec": 1700600259235,
  "archethicOracleUCO": null,
  "htlcAEAddress": "000023816eedb1ceb48e745317043b052831ef2a71b41118c3b03501e38fc78b96e8",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

coinbase

**Comment by redDwarf03** [comment] 2024-10-24 06:49
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:49 UTC
Labels: Bug, In triage, Campaign: Bridge
