### ISSUE TITLE
[Bug]: Clover wallet - ETH - ETH>ARCH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#59] opened 2023-11-23 00:27 UTC
### Description

Clover wallet 
Send ETH from Sepolia ethereum testnet to archethic testnet 

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/4e12a65f-e830-460a-aa50-d4a085628fad)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "blockchainTo": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": null,
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "tokenToBridge": {
    "name": "Ether",
    "tokenAddressSource": "",
    "tokenAddressTarget": "00003DF600E329199BF3EE8FBE2B8223413D70BCDD97E15089E6A74D94DE3F1173B4",
    "symbol": "ETH",
    "targetTokenName": "Archethic Ether",
    "targetTokenSymbol": "aeETH",
    "poolAddressFrom": "0xcfBA4FA32527bFf23E073406c772e9a8b8D02650",
    "poolAddressTo": "000066706d704329ca8c2a4153991e2ddacc968622ca10217ca14952eb7abb966c30",
    "type": "Native"
  },
  "tokenToBridgeAmount": 0.05,
  "targetAddress": "00001675becda24450fad82114a15b58567979e8e7aea1cffc54ce8c1779513ea2af",
  "tokenToBridgeBalance": 0.13,
  "tokenBridgedBalance": 0.0600493,
  "poolTargetBalance": 0,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "NoSuchMethodError: method not found: 'i' on null",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "evm",
  "currentStep": 1,
  "changeDirectionInProgress": false,
  "timestampExec": 1700699116653,
  "archethicOracleUCO": null,
  "htlcAEAddress": null,
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": "0x50f1a1ec99cdb1a5c3425281ee96e9e85a8b891f58c88a97721d12582bd5b334",
  "secret": [
    178,
    142,
    91,
    205,
    227,
    206,
    139,
    70,
    146,
    86,
    209,
    197,
    18,
    123,
    64,
    164,
    86,
    111,
    182,
    200,
    89,
    240,
    242,
    212,
    212,
    32,
    223,
    166,
    7,
    225,
    163,
    23
  ],
  "safetyModuleFeesRate": 0.5,
  "safetyModuleFeesAddress": "0x57B5Fe2F6A28E108208BA4965d9879FACF629442",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

Clover

**Comment by redDwarf03** [comment] 2024-10-24 06:47
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:47 UTC
Labels: Bug, In triage, Campaign: Bridge
