### ISSUE TITLE
[Bug]: coinbase wallet - aeETH - ARCH>POLY

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#53] opened 2023-11-21 21:19 UTC
### Description

Wallet coinbase 
Send UCO from Archethic testnet to Mumbai Polygon Testnet

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/c231b98d-0d0d-4c8b-be1d-721db6f67630)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000a84e0fe7629a5d164bcb4b7ddd2227b1d45f5a8ce75529830a75cb18e4e9ee86",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Mumbai Polygon Testnet",
    "chainId": 80001,
    "env": "2-testnet",
    "icon": "Polygon.svg",
    "urlExplorerAddress": "https://mumbai.polygonscan.com/address/",
    "urlExplorerTransaction": "https://mumbai.polygonscan.com/tx/",
    "providerEndpoint": "https://polygon-mumbai.g.alchemy.com/v2/DynWKvz6PUFaeZNmlxPXNiV1nK4Ac_2D",
    "isArchethic": false,
    "nativeCurrency": "MATIC",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Universal Coin",
    "tokenAddressSource": "",
    "tokenAddressTarget": "0x51279e98d99AA8D65763a885BEFA5463dCd84Af6",
    "symbol": "UCO",
    "targetTokenName": "ERC20 - Universal Coin",
    "targetTokenSymbol": "UCO",
    "poolAddressFrom": "000018d60115ece0c7558a46b4693749bf6beab524fddccf9b10b910619e4ee08801",
    "poolAddressTo": "0xe55915D112711127339f073e75185E6311Dd72C8",
    "type": "Native"
  },
  "tokenToBridgeAmount": 10,
  "targetAddress": "0x532bce2c4919788c8ba3d84159714014a4028eeb",
  "tokenToBridgeBalance": 492.87375116,
  "tokenBridgedBalance": 0,
  "poolTargetBalance": 34117.32476864898,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "cause": "FormatException: SyntaxError: Unexpected token 'F', \"Failed to \"... is not valid JSON",
    "stack": null,
    "runtimeType": "other"
  },
  "isTransferInProgress": false,
  "walletConfirmation": "evm",
  "currentStep": 4,
  "changeDirectionInProgress": false,
  "timestampExec": 1700601191278,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000a84e0fe7629a5d164bcb4b7ddd2227b1d45f5a8ce75529830a75cb18e4e9ee86",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

coinbase

**Comment by redDwarf03** [comment] 2024-10-24 06:50
Hello
Thank you for this feedback. During the various phases of development, testing and user feedback, these problems were neither observed nor reproduced, unfortunately. Perhaps this is due to a component present on your computer. We close this issue

**Closed by redDwarf03** 2024-10-24 06:50 UTC
Labels: Bug, Invalid, Campaign: Bridge
